### ISSUE TITLE
Need to know the usage of modals in phaser 

### ISSUE THREAD

**Issue by Tdnshah** [netgfx/phaser_modals#8]
I want to use this modals in my game to create popups. I tired using this by interacting the modal.js. But still i am unable to create popups using this modal.js file in my game. If any one can help with the detailed documentation of how to use this will be a great a help.

**Comment by netgfx** [comment]
ok I have reviewed your code from here: https://github.com/Tdnshah/Phaser-Pattern-Games/blob/a0f86ade77bdda8da2f69cca767e694a6befe974/src/game1.js

You are creating the modal with `this.createModal();` 

but you are never showing it with `reg.modal.showModal("modal1");`
when we create a modal it is always hidden, because we might want to create all modals before we start the game. So in order to show an already created modal just call

`reg.modal.showModal(MODAL-NAME);`

This codepen might help you understand more: http://codepen.io/netgfx/pen/bNLgaX
so there we have the `createModals();` function that creates the modals but none appear. 
We have to press a button like this one `var m1 = this.game.add.button(30, 50, "m1", showModal1);`
and this calls
```javascript
function showModal1(){
  reg.modal.showModal("modal1");
}
```

I hope its more clear now. Let me know if you need more help with this.

**Comment by Tdnshah** [comment]
@netgfx  thanks a lot for the reply.
I tried what you have mentioned in the above comment. But now i get errors like  
"Uncaught TypeError: Cannot set property 'modals' of undefined"

Also Yesterday i had tried replacing the game inside reg.modal = new gameModal(game); with my game object i.e (patternsRatio) and also replacing all the game.xxx patternsRatio in modals.js file that time i was getting error  "Uncaught TypeError: Cannot set property 'modal1' of undefined"

May be i am unable to under stand this java script objects properly

so request you if you can help resolve

**Comment by netgfx** [comment]
please share your code so I can identify the problem.

**Comment by Tdnshah** [comment]
@netgfx thank for you prompt response

here is the fiddle link to the code i tried https://jsfiddle.net/oc496u3r/

**Comment by netgfx** [comment]
You have a global variable `var reg = {};` and a local one on line `84` there should only exist one global variable `reg`. Remove the one on line 84 and try again. I cannot debug further because the game isn't running

**Comment by Tdnshah** [comment]
i tried this is to but the same error persist:
You can get the complete game from my git @ https://github.com/Tdnshah/Phaser-Pattern-Games.git
you can take the pull for the running the game. As i had one made a fiddle of one file you could not run the game.

@netgfx  i have also requested to join phaserjs slack group so if you can accept and request please add me also to the slack...

**Comment by netgfx** [comment]
I don't own that channel but I'm sure Richard Davey will accept you request soon.

I will try and run your game from the repo, just make sure you have the code in the state that you are right now containing all of my suggestions.

Thanks.

**Comment by Tdnshah** [comment]
@netgfx  i have also just now updated my git repo as per your request .. 

Thanks a lot for the help

**Comment by netgfx** [comment]
@Tdnshah ok if you call the modal constructor like this it works:
`reg.modal = new gameModal(patternsRatio.game);`
